# Generated by Django 5.0.6 on 2024-07-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_userprofile_acudiente_userprofile_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
