# Generated by Django 5.0.6 on 2024-07-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_userprofile_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='numero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
