# Generated by Django 5.0.6 on 2024-07-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_valoracion_numero_valoracion_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='cepillado_dental',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No')]),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='diabetes',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No'), (3, 'Desinformado')], default=3),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='enfermedad_respiratoria',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No'), (3, 'Desinformado')], default=3),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='enjuague_bucal',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No')]),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='reacciones_alergicas',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No'), (3, 'Desinformado')], default=3),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='seda_dental',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No')]),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='transtorno_tension_arterial',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No'), (3, 'Desinformado')], default=3),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='transtornos_emocionales',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No'), (3, 'Desinformado')], default=3),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='tratamiento_medicacion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No'), (3, 'Desinformado')], default=3),
        ),
    ]
