# Generated by Django 5.0.6 on 2024-07-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_valoracion_cepillado_dental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='fecha_historia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
