# Generated by Django 5.0.6 on 2024-07-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_valoracion_fecha_historia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fecha_ingreso',
        ),
    ]
