# Generated by Django 5.0.6 on 2024-07-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_alter_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=150)),
                ('cantidad', models.FloatField(blank=True, max_length=50)),
                ('estado', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
