# Generated by Django 5.0.6 on 2024-07-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('por_recibir', 'Por Recibir')]),
        ),
    ]
