# Generated by Django 5.0.6 on 2024-07-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_alter_inventario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Disponible'), ('2', 'Agotado'), ('3', 'Por Recibir')]),
        ),
    ]
