# Generated by Django 5.0.6 on 2024-07-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_alter_inventario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.FloatField(blank=True),
        ),
    ]
