# Generated by Django 5.0.6 on 2024-07-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_alter_inventario_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=150)),
                ('cantidad', models.FloatField(blank=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Disponible'), (2, 'Agotado'), (3, 'Por Recibir')])),
            ],
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
            options={
                'unique_together': {('fecha', 'hora')},
            },
        ),
    ]
