# Generated by Django 5.0.6 on 2024-07-15 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_remove_cita_cantidad_remove_cita_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.fecha'),
        ),
    ]
