# Generated by Django 5.0.6 on 2024-07-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_alter_cita_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
