# Generated by Django 5.0.6 on 2024-07-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_cita_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='username',
        ),
        migrations.AddField(
            model_name='cita',
            name='numero',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
