# Generated by Django 5.0.6 on 2024-07-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_alter_cita_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='numero',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
