# Generated by Django 5.0.6 on 2024-07-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0036_alter_cita_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='numero',
        ),
    ]
