# Generated by Django 5.0.6 on 2024-07-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0037_remove_cita_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='fecha',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
