# Generated by Django 5.0.6 on 2024-07-17 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0038_fecha_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='login.fecha'),
        ),
    ]
