# Generated by Django 5.0.6 on 2024-07-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0039_alter_cita_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='numero',
            field=models.BigIntegerField(unique=True),
        ),
    ]
